# Generated by Django 4.0.10 on 2024-04-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_industry_leadinformation_companyinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinformation',
            name='lead_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinformation',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadinformation',
            name='status_label',
            field=models.IntegerField(blank=True, choices=[(1, 'uncontacted'), (2, 'contacted'), (3, 'pipeline'), (4, 'close deal'), (5, 'reassign')], null=True),
        ),
        migrations.AddField(
            model_name='leadinformation',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'b2b'), (2, 'b2c')], null=True),
        ),
        migrations.AlterField(
            model_name='leadinformation',
            name='status',
            field=models.IntegerField(choices=[(1, 'untouched'), (2, 'qualification'), (3, 'follow up'), (4, 'cold leads'), (5, 'presentation'), (6, 'proposal'), (7, 'negotiation'), (4, 'close deal'), (9, 'lost deal'), (5, 'reassign'), (11, 'do not call')], default=1),
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'inactive')], default=1)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation')),
            ],
        ),
        migrations.CreateModel(
            name='LeadOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'transfered'), (2, 'on progress'), (3, 'done')], default=2)),
                ('date_handle', models.DateField()),
                ('date_transfer', models.DateField()),
                ('date_completed', models.DateField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation')),
            ],
        ),
    ]
