# Generated by Django 4.0.10 on 2024-04-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leadinformation_lead_score_leadinformation_source_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadOwners',
            new_name='LeadOwner',
        ),
    ]
