# Generated by Django 4.0.10 on 2024-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_leadowners_leadowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadinformation',
            name='department',
        ),
        migrations.AlterField(
            model_name='leadowner',
            name='date_handle',
            field=models.DateField(auto_now_add=True),
        ),
    ]
