# Generated by Django 4.0.10 on 2024-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_leadinformation_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
