# Generated by Django 4.0.10 on 2024-04-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_leadowner_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinformation',
            name='date_close_deal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinformation',
            name='date_contacted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
