# Generated by Django 4.0.10 on 2024-04-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, 'manager'), (3, 'staff'), (4, 'external'), (1, 'admin')], null=True),
        ),
    ]
