# Generated by Django 4.0.10 on 2024-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinformation',
            name='status_label',
            field=models.IntegerField(choices=[(1, 'uncontacted'), (2, 'contacted'), (3, 'pipeline'), (4, 'close deal'), (5, 'reassign')], default=1),
        ),
    ]
