# Generated by Django 4.0.10 on 2024-04-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_leadowner_date_handle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerhistory',
            old_name='account',
            new_name='last_owner',
        ),
    ]
