# Generated by Django 4.0.10 on 2024-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_account_ownerhistory_last_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadowner',
            name='date_handle',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
