# Generated by Django 4.0.10 on 2024-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadowner',
            name='date_handle',
            field=models.DateField(blank=True, null=True),
        ),
    ]
