# Generated by Django 4.0.10 on 2024-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_leadowner_date_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerhistory',
            name='date_handle',
            field=models.DateField(blank=True, null=True),
        ),
    ]
