# Generated by Django 4.0.10 on 2024-04-21 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ownerhistory_date_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'edited'), (3, 'deleted')], default=1)),
                ('date_noted', models.DateField(blank=True, null=True)),
                ('date_edited', models.DateField(blank=True, null=True)),
                ('lead_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation')),
            ],
        ),
    ]
