# Generated by Django 4.0.10 on 2024-04-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='remarks',
        ),
        migrations.AddField(
            model_name='leadinformation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
