# Generated by Django 4.0.10 on 2024-04-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_client_remarks_leadinformation_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date_edited',
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'deleted')], default=1),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'deleted')], default=1)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'new leads'), (2, 'update status'), (3, 'service')], null=True)),
                ('date_generated', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation')),
            ],
        ),
    ]
