# Generated by Django 4.0.10 on 2024-04-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_notes_date_edited_alter_notes_status_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_noted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
