# Generated by Django 4.0.10 on 2024-04-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_activity_date_generated_alter_notes_date_noted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffered',
            name='lead',
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
