# Generated by Django 4.0.10 on 2024-04-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_serviceoffered_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('msf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ongoing'), (2, 'done'), (3, 'hold')], default=1)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lead_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceoffered')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.IntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True)),
                ('month_end', models.IntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('lead_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadservices')),
            ],
        ),
    ]
