# Generated by Django 4.0.10 on 2024-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_leadservices_monthlyterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'new leads'), (2, 'update status'), (3, 'update info')], null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
