# Generated by Django 4.2.11 on 2024-04-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_termstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadservices',
            old_name='projected_revenue',
            new_name='revenue',
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('projected_otf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('projected_msf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lead_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadservices')),
            ],
        ),
    ]
