# Generated by Django 4.2.11 on 2024-05-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_projected_revenue_leadservices_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termstatus',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'paid'), (3, 'unpaid'), (1, 'default')], null=True),
        ),
    ]
