# Generated by Django 4.2.13 on 2024-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_termstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'admin'), (2, 'manager'), (3, 'staff'), (4, 'external')], null=True),
        ),
    ]
