# Generated by Django 4.2.13 on 2024-05-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='lead_owner',
        ),
        migrations.AddField(
            model_name='archive',
            name='lead_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation'),
        ),
    ]
