# Generated by Django 4.2.13 on 2024-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_archive_lead_owner_archive_lead_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'admin'), (2, 'manager'), (3, 'staff'), (4, 'external'), (5, 'general manager')], null=True),
        ),
    ]
