# Generated by Django 4.2.13 on 2024-06-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinformation',
            name='status',
            field=models.IntegerField(choices=[(1, 'untouched'), (2, 'qualification'), (3, 'follow up'), (4, 'cold leads'), (5, 'presentation'), (6, 'proposal'), (7, 'negotiation'), (8, 'close deal'), (9, 'lost deal'), (10, 'reassign'), (11, 'do not call')], default=1),
        ),
    ]
