# Generated by Django 4.2.13 on 2024-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_leadinformation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='termstatus',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
