# Generated by Django 4.2.13 on 2024-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_leadservices_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadservices',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
