# Generated by Django 4.2.13 on 2024-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_leadservices_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadservices',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
