# Generated by Django 4.2.13 on 2024-06-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_leadservices_revenue'),
        ('core', '0043_leadservices_otf_payment'),
    ]

    operations = [
    ]
