# Generated by Django 4.2.13 on 2024-06-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20240619_1535'),
        ('core', '0045_alter_leadservices_msf'),
    ]

    operations = [
    ]
