# Generated by Django 4.2.13 on 2024-07-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20240621_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inserted', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('lead_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadservices')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account')),
            ],
        ),
    ]
