# Generated by Django 4.2.13 on 2024-07-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='lead_service',
        ),
        migrations.AddField(
            model_name='attachment',
            name='lead_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leadinformation'),
        ),
    ]
