# Generated by Django 4.2.13 on 2024-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_attachment_lead_service_attachment_lead_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='termstatus',
            name='msf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
