# Generated by Django 4.2.16 on 2024-11-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prouct_code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_on_hand', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lead_info',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='lead_info',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='lead_info',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='leadinformation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='leadowner',
            name='account',
        ),
        migrations.RemoveField(
            model_name='leadowner',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadservices',
            name='lead_info',
        ),
        migrations.RemoveField(
            model_name='leadservices',
            name='service',
        ),
        migrations.RemoveField(
            model_name='monthlyterms',
            name='lead_service',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='lead_info',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='ownerhistory',
            name='last_owner',
        ),
        migrations.RemoveField(
            model_name='ownerhistory',
            name='lead_owner',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='lead_service',
        ),
        migrations.RemoveField(
            model_name='termstatus',
            name='lead_service',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='CompanyInformation',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='LeadInformation',
        ),
        migrations.DeleteModel(
            name='LeadOwner',
        ),
        migrations.DeleteModel(
            name='LeadServices',
        ),
        migrations.DeleteModel(
            name='MonthlyTerms',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='OwnerHistory',
        ),
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
        migrations.DeleteModel(
            name='ServiceOffered',
        ),
        migrations.DeleteModel(
            name='TermStatus',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userinfo'),
        ),
    ]
